### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by erinmgriffith** [erinmgriffith/Active-projects#112]
- [ ] research how detailed google analytics source referral tracking is
- [ ] how to track customers we have referred but do not go thru quote page?
- [ ] create plan to assign customer id to each quote click as 
      flag that direct interaction with customer has begun.  
- [ ] write summary and create flow chart to track all. 
- [ ] Make code reusable for future markatability.

**Comment by chrismkim** [comment]
Coupon Codes can be used to track which sale comes from which source. Each blogger can have their own code.
