### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by erinmgriffith** [erinmgriffith/Active-projects#143]
- [ ] research and create tracking system that performs the following functions-
    - [ ] includes google analytics and FB pixel
    - [ ] track traffic sources 
    - [ ] tracks demographics
    - [ ]  captures email at time of "submit quote"
    - [ ] creates signature on submit to know that the referral was through one of our efforts.
    - [ ]  store email and customer info - DB?

**Comment by erinmgriffith** [comment]
Duplicate issue
